server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://ls-dadd6ea104784a8dd6f671234507d639f605d304.cz3el1yeom5t.ap-south-1.rds.amazonaws.com:3306/mediconnectauth
    username: dbmasteruser
    password: mediconnect98
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: AUTH-SERVICE

    config:
      import: configserver:http://localhost:9296
    profiles:
      active: test
#  config:
#    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
